"""
Long-Term Simulator Module

Generates multi-day simulation scenarios with predefined patterns
"""

import random
import logging
import time
from datetime import datetime, timedelta
from typing import List, Tuple

from ..data.schema import (
    SimulationScenario, SimulationConfig, SimulationResult,
    Event, EventType, DataSourceMode
)
from ..storage.database import Database
from .baseline_simulator import BaselineSimulator
from .simulation_generator import SimulationGenerator


logger = logging.getLogger(__name__)


class LongTermSimulator:
    """Generates multi-day simulation scenarios"""
    
    # Scenario parameters
    NORMAL_VISITS_PER_DAY = (2, 4)
    NORMAL_DURATION = (30, 120)  # seconds
    
    POLYURIA_VISITS_PER_DAY = (6, 10)
    POLYURIA_DURATION = (15, 45)  # seconds
    POLYURIA_ONSET_DAY = 3
    
    WEIGHT_LOSS_RATE_PER_DAY = (0.005, 0.010)  # 0.5-1.0% per day
    
    # Time distribution (avoid nighttime 23:00-06:00)
    ACTIVE_HOURS = list(range(6, 23))  # 06:00-22:59
    
    # Validation constraints
    MAX_EVENTS_PER_DAY = 15
    MIN_EVENT_DURATION = 10  # seconds
    MAX_EVENT_DURATION = 300  # seconds
    MIN_INTERVAL_HOURS = 2  # minimum hours between events for same cat
    WEIGHT_TOLERANCE = 0.20  # ±20% of profile weight
    MIN_FINAL_WEIGHT_RATIO = 0.70  # 70% of starting weight
    
    def __init__(self, database: Database, baseline_simulator: BaselineSimulator,
                 simulation_generator: SimulationGenerator):
        """
        Initialize long-term simulator
        
        Args:
            database: Database instance
            baseline_simulator: BaselineSimulator instance
            simulation_generator: SimulationGenerator instance
        """
        self.db = database
        self.baseline_simulator = baseline_simulator
        self.sim_generator = simulation_generator
    
    def run_simulation(self, config: SimulationConfig) -> SimulationResult:
        """
        Execute long-term simulation
        
        Args:
            config: SimulationConfig
            
        Returns:
            SimulationResult
        """
        start_time = time.time()
        errors = []
        
        # Validate configuration
        validation_errors = self.validate_config(config)
        if validation_errors:
            logger.error(f"Configuration validation failed: {validation_errors}")
            return SimulationResult(
                config=config,
                events_generated=0,
                alerts_created=0,
                weight_changes={},
                baseline_changes=0,
                execution_time=0,
                errors=validation_errors
            )
        
        logger.info(f"Starting {config.duration_days}-day simulation for {len(config.cats)} cat(s)")
        
        events_generated = 0
        baseline_changes = 0
        weight_changes = {}
        
        # Generate events for each cat
        for cat_id, scenario in config.cats:
            try:
                cat_profile = self.db.get_cat_profile(cat_id)
                if not cat_profile:
                    errors.append(f"Cat profile not found: {cat_id}")
                    continue
                
                logger.info(f"Generating events for {cat_profile.name} ({scenario.value})")
                
                # Record starting weight
                starting_weight = cat_profile.baseline_weight
                
                # Generate events
                end_date = config.start_datetime + timedelta(days=config.duration_days)
                events = self.generate_events_for_cat(
                    cat_id, scenario, config.start_datetime, end_date
                )
                
                events_generated += len(events)
                
                # Calculate final weight
                if events:
                    final_weight = events[-1].avg_weight - events[-1].baseline_before
                    change_rate = ((final_weight - starting_weight) / starting_weight) * 100
                    weight_changes[cat_id] = (starting_weight, final_weight, change_rate)
                
            except Exception as e:
                error_msg = f"Error generating events for cat {cat_id}: {e}"
                logger.error(error_msg)
                errors.append(error_msg)
        
        execution_time = time.time() - start_time
        
        # Count alerts (would be generated by AlertGenerator in real usage)
        alerts_created = 0  # Placeholder
        
        result = SimulationResult(
            config=config,
            events_generated=events_generated,
            alerts_created=alerts_created,
            weight_changes=weight_changes,
            baseline_changes=baseline_changes,
            execution_time=execution_time,
            errors=errors
        )
        
        logger.info(f"Simulation completed: {events_generated} events in {execution_time:.1f}s")
        
        return result
    
    def generate_events_for_cat(self, cat_id: str, scenario: SimulationScenario,
                                start_date: datetime, end_date: datetime) -> List[Event]:
        """
        Generate events for one cat over period
        
        Args:
            cat_id: Cat ID
            scenario: SimulationScenario
            start_date: Start datetime
            end_date: End datetime
            
        Returns:
            List of generated Events
        """
        cat_profile = self.db.get_cat_profile(cat_id)
        if not cat_profile:
            return []
        
        events = []
        current_date = start_date
        day_number = 0
        current_weight = cat_profile.baseline_weight
        
        while current_date < end_date:
            day_number += 1
            
            # Apply scenario pattern
            num_visits, weight = self.apply_scenario_pattern(
                scenario, day_number, 
                random.randint(*self.NORMAL_VISITS_PER_DAY),
                current_weight
            )
            
            current_weight = weight
            
            # Generate event timestamps for this day
            event_times = self.distribute_events_in_day(num_visits, current_date)
            
            # Create events
            for event_time in event_times:
                # Determine duration based on scenario
                if scenario in [SimulationScenario.POLYURIA_ONSET, SimulationScenario.COMBINED]:
                    if day_number > self.POLYURIA_ONSET_DAY:
                        duration = random.uniform(*self.POLYURIA_DURATION)
                    else:
                        duration = random.uniform(*self.NORMAL_DURATION)
                else:
                    duration = random.uniform(*self.NORMAL_DURATION)
                
                # Get current baseline
                baseline = self.baseline_simulator.baseline_manager.get_current_baseline()
                
                # Create event
                event = Event(
                    event_id=f"sim-{cat_id}-{event_time.isoformat()}",
                    device_id="simulator",
                    cat_id=cat_id,
                    event_type=EventType.CAT_VISIT,
                    start_time=event_time,
                    end_time=event_time + timedelta(seconds=duration),
                    duration=duration,
                    baseline_before=baseline,
                    baseline_after=baseline,
                    max_weight=baseline + current_weight + random.uniform(-0.1, 0.1),
                    avg_weight=baseline + current_weight,
                    weight_gain=current_weight,
                    baseline_shift=0.0,
                    stability_score=random.uniform(0.85, 0.98),
                    confidence_score=random.uniform(0.80, 0.95),
                    data_source=DataSourceMode.SIMULATION
                )
                
                events.append(event)
                self.db.save_event(event)
                
                # Apply baseline fluctuation
                if random.random() < 0.3:  # 30% chance of urination effect
                    self.baseline_simulator.apply_urination_effect()
                elif random.random() < 0.1:  # 10% chance of defecation effect
                    self.baseline_simulator.apply_defecation_effect()
                
                # Check for auto-maintenance
                maintenance = self.baseline_simulator.check_auto_maintenance()
                if maintenance == "refill":
                    self.baseline_simulator.apply_refill_effect()
                elif maintenance == "cleaning":
                    self.baseline_simulator.apply_cleaning_effect()
            
            # Move to next day
            current_date += timedelta(days=1)
        
        return events
    
    def apply_scenario_pattern(self, scenario: SimulationScenario, day: int,
                               base_visits: int, base_weight: float) -> Tuple[int, float]:
        """
        Apply scenario modifications
        
        Args:
            scenario: SimulationScenario
            day: Day number (1-indexed)
            base_visits: Base number of visits
            base_weight: Base weight
            
        Returns:
            Tuple of (visits, weight)
        """
        visits = base_visits
        weight = base_weight
        
        if scenario == SimulationScenario.NORMAL:
            # No modifications
            pass
        
        elif scenario == SimulationScenario.POLYURIA_ONSET:
            if day > self.POLYURIA_ONSET_DAY:
                visits = random.randint(*self.POLYURIA_VISITS_PER_DAY)
        
        elif scenario == SimulationScenario.GRADUAL_WEIGHT_LOSS:
            daily_loss_rate = random.uniform(*self.WEIGHT_LOSS_RATE_PER_DAY)
            weight *= (1 - daily_loss_rate)
        
        elif scenario == SimulationScenario.COMBINED:
            # Apply both polyuria and weight loss
            if day > self.POLYURIA_ONSET_DAY:
                visits = random.randint(*self.POLYURIA_VISITS_PER_DAY)
            daily_loss_rate = random.uniform(*self.WEIGHT_LOSS_RATE_PER_DAY)
            weight *= (1 - daily_loss_rate)
        
        return visits, weight
    
    def distribute_events_in_day(self, num_events: int, date: datetime) -> List[datetime]:
        """
        Distribute events across realistic times in day
        
        Args:
            num_events: Number of events to distribute
            date: Date for events
            
        Returns:
            List of event datetimes
        """
        event_times = []
        
        for _ in range(num_events):
            # Choose random hour from active hours
            hour = random.choice(self.ACTIVE_HOURS)
            minute = random.randint(0, 59)
            second = random.randint(0, 59)
            
            event_time = date.replace(hour=hour, minute=minute, second=second)
            event_times.append(event_time)
        
        # Sort chronologically
        event_times.sort()
        
        return event_times
    
    def validate_config(self, config: SimulationConfig) -> List[str]:
        """
        Validate simulation configuration
        
        Args:
            config: SimulationConfig
            
        Returns:
            List of error messages (empty if valid)
        """
        errors = []
        
        # Check duration
        if config.duration_days not in [7, 14, 30]:
            errors.append(f"Invalid duration: {config.duration_days} (must be 7, 14, or 30)")
        
        # Check cats
        if not config.cats:
            errors.append("No cats selected for simulation")
        
        # Check cat profiles exist
        for cat_id, scenario in config.cats:
            profile = self.db.get_cat_profile(cat_id)
            if not profile:
                errors.append(f"Cat profile not found: {cat_id}")
        
        return errors
